name       : glib-networking
version    : 2.60.2
release    : 23
source     :
    - https://download.gnome.org/sources/glib-networking/2.60/glib-networking-2.60.2.tar.xz : c022f3d10f55a5b7c31676fb001b4cb6401db8ab9f6e8418c69de00d0f268732
homepage   : http://www.gnome.org
license    : GPL-2.0-only
component  : network.base
summary    : The GLib Networking package contains Network related gio modules for GLib.
description: |
    The GLib Networking package contains Network related gio modules for GLib.
emul32     : yes
builddeps  :
    - pkgconfig32(glib-2.0)
    - pkgconfig32(gnutls)
    - pkgconfig32(libtasn1)
    - pkgconfig32(nettle)
    - pkgconfig32(nettle)
    - pkgconfig32(openssl)
    - pkgconfig(libtasn1)
    - pkgconfig(nettle)
    - gmp-32bit-devel
    - libtool-32bit
    - libunistring-32bit-devel
setup      : |
    %meson_configure \
           -Dgnome_proxy_support=false \
           -Dinstalled_tests=false \
           -Dlibproxy_support=false \
           -Dopenssl="enabled" \
           -Dstatic_modules=false
build      : |
    unset LD_AS_NEEDED
    %ninja_build
install    : |
    unset LD_AS_NEEDED
    %ninja_install
