name        : glib-networking
version     : 2.44.0
release     : 10
source      :
    - http://ftp.gnome.org/pub/gnome/sources/glib-networking/2.44/glib-networking-2.44.0.tar.xz : 8f8a340d3ba99bfdef38b653da929652ea6640e27969d29f7ac51fbbe11a4346
homepage    : http://www.gnome.org
license     :
    - GPL-2.0
summary     : The GLib Networking package contains Network related gio modules for GLib.
builddeps   :
    - pkgconfig(p11-kit-1)
    - pkgconfig(gnutls)
    - pkgconfig(libtasn1)
    - pkgconfig(nettle)
description : |
    The GLib Networking package contains Network related gio modules for GLib.
setup      : |
    %configure --disable-static \
               --with-ca-certificates=/etc/ssl/certs/ca-certificates.crt
build      : |
    %make
install    : |
    %make_install
