name       : glib-networking
version    : 2.76.1
release    : 45
source     :
    - https://download.gnome.org/sources/glib-networking/2.76/glib-networking-2.76.1.tar.xz : 5c698a9994dde51efdfb1026a56698a221d6250e89dc50ebcddda7b81480a42b
homepage   : http://www.gnome.org
license    : GPL-2.0-only
component  : network.base
summary    : The GLib Networking package contains Network related gio modules for GLib.
description: |
    The GLib Networking package contains Network related gio modules for GLib.
emul32     : yes
builddeps  :
    - pkgconfig32(glib-2.0)
    - pkgconfig32(gnutls)
    - pkgconfig32(libtasn1)
    - pkgconfig32(nettle)
    - pkgconfig32(nettle)
    - pkgconfig32(openssl)
    - pkgconfig(libtasn1)
    - pkgconfig(libproxy-1.0)
    - pkgconfig(nettle)
    - gmp-32bit-devel
    - libtool-32bit
    - libunistring-32bit-devel
    # Temporary, remove after openssl 3.1 rebuilds are done
    - openssl-32bit-devel
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        proxy_setting="disabled"
    else
        proxy_setting="enabled"
    fi

    %meson_configure \
           -Dgnome_proxy=disabled \
           -Dinstalled_tests=false \
           -Dlibproxy=$proxy_setting \
           -Dopenssl="enabled" 
build      : |
    unset LD_AS_NEEDED
    %ninja_build
install    : |
    unset LD_AS_NEEDED
    %ninja_install
