name       : glib-networking
version    : 2.64.1
release    : 29
source     :
    - https://download.gnome.org/sources/glib-networking/2.64/glib-networking-2.64.1.tar.xz : a4c346def7d817467d79a95c23b3ccf22e4df1548870726b63396400852daf72
homepage   : http://www.gnome.org
license    : GPL-2.0-only
component  : network.base
summary    : The GLib Networking package contains Network related gio modules for GLib.
description: |
    The GLib Networking package contains Network related gio modules for GLib.
emul32     : yes
builddeps  :
    - pkgconfig32(glib-2.0)
    - pkgconfig32(gnutls)
    - pkgconfig32(libtasn1)
    - pkgconfig32(nettle)
    - pkgconfig32(nettle)
    - pkgconfig32(openssl)
    - pkgconfig(libtasn1)
    - pkgconfig(nettle)
    - gmp-32bit-devel
    - libtool-32bit
    - libunistring-32bit-devel
setup      : |
    %meson_configure \
           -Dgnome_proxy_support=false \
           -Dinstalled_tests=false \
           -Dlibproxy_support=false \
           -Dopenssl="enabled" \
           -Dstatic_modules=false
build      : |
    unset LD_AS_NEEDED
    %ninja_build
install    : |
    unset LD_AS_NEEDED
    %ninja_install
