name       : glib-networking
version    : 2.62.3
release    : 27
source     :
    - https://download.gnome.org/sources/glib-networking/2.62/glib-networking-2.62.3.tar.xz : 8ca1f86f23a76b5c7640624f7d5490705c78e81375e1741c9a1c41ce7f8f7ff7
homepage   : http://www.gnome.org
license    : GPL-2.0-only
component  : network.base
summary    : The GLib Networking package contains Network related gio modules for GLib.
description: |
    The GLib Networking package contains Network related gio modules for GLib.
emul32     : yes
builddeps  :
    - pkgconfig32(glib-2.0)
    - pkgconfig32(gnutls)
    - pkgconfig32(libtasn1)
    - pkgconfig32(nettle)
    - pkgconfig32(nettle)
    - pkgconfig32(openssl)
    - pkgconfig(libtasn1)
    - pkgconfig(nettle)
    - gmp-32bit-devel
    - libtool-32bit
    - libunistring-32bit-devel
setup      : |
    %meson_configure \
           -Dgnome_proxy_support=false \
           -Dinstalled_tests=false \
           -Dlibproxy_support=false \
           -Dopenssl="enabled" \
           -Dstatic_modules=false
build      : |
    unset LD_AS_NEEDED
    %ninja_build
install    : |
    unset LD_AS_NEEDED
    %ninja_install
