name       : glib-networking
version    : 2.68.2
release    : 35
source     :
    - https://download.gnome.org/sources/glib-networking/2.68/glib-networking-2.68.2.tar.xz : 535ebc054ef697db56a4fffed91bc0e11c8ee1c9acb48aad28c8e1d5c3d5994f
homepage   : http://www.gnome.org
license    : GPL-2.0-only
component  : network.base
summary    : The GLib Networking package contains Network related gio modules for GLib.
description: |
    The GLib Networking package contains Network related gio modules for GLib.
emul32     : yes
builddeps  :
    - pkgconfig32(glib-2.0)
    - pkgconfig32(gnutls)
    - pkgconfig32(libtasn1)
    - pkgconfig32(nettle)
    - pkgconfig32(nettle)
    - pkgconfig(libtasn1)
    - pkgconfig(libproxy-1.0)
    - pkgconfig(nettle)
    - gmp-32bit-devel
    - libtool-32bit
    - libunistring-32bit-devel
    - openssl-11-32bit-devel
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        proxy_setting="disabled"
    else
        proxy_setting="enabled"
    fi

    %meson_configure \
           -Dgnome_proxy=disabled \
           -Dinstalled_tests=false \
           -Dlibproxy=$proxy_setting \
           -Dopenssl="enabled" \
           -Dstatic_modules=false
build      : |
    unset LD_AS_NEEDED
    %ninja_build
install    : |
    unset LD_AS_NEEDED
    %ninja_install
