name       : glib-networking
version    : 2.48.2
release    : 14
source     :
    - http://ftp.gnome.org/pub/gnome/sources/glib-networking/2.48/glib-networking-2.48.2.tar.xz : 925c0c49d6b2b8b5695f2e33cd952d1dbb7d18d3f2f796413577719315bb3a84
homepage   : http://www.gnome.org
license    :
    - GPL-2.0
summary    : The GLib Networking package contains Network related gio modules for GLib.
builddeps  :
    - pkgconfig(p11-kit-1)
    - pkgconfig32(p11-kit-1)
    - pkgconfig(gnutls)
    - pkgconfig32(gnutls)
    - pkgconfig(libtasn1)
    - pkgconfig32(libtasn1)
    - pkgconfig(nettle)
    - pkgconfig32(nettle)
    - pkgconfig32(glib-2.0)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    The GLib Networking package contains Network related gio modules for GLib.
setup      : |
    %configure --disable-static \
               --with-ca-certificates=/etc/ssl/certs/ca-certificates.crt \
               --prefix=/usr \
               --disable-more-warnings
build      : |
    %make
install    : |
    %make_install
