name       : glib-networking
version    : 2.54.0
release    : 17
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/glib-networking/2.54/glib-networking-2.54.0.tar.xz : 5961b3779080b72314b373ff5d4790eb7e41b75ca91816ad7a81ef32922f7096
homepage   : http://www.gnome.org
license    :
    - GPL-2.0
summary    : The GLib Networking package contains Network related gio modules for GLib.
builddeps  :
    - pkgconfig32(nettle)
    - pkgconfig32(p11-kit-1)
    - pkgconfig32(gnutls)
    - pkgconfig(libtasn1)
    - pkgconfig32(libtasn1)
    - pkgconfig(nettle)
    - pkgconfig32(nettle)
    - pkgconfig32(glib-2.0)
    - libunistring-32bit-devel
    - libtool-32bit
    - gmp-32bit-devel
emul32     : yes
component  : network.base
description: |
    The GLib Networking package contains Network related gio modules for GLib.
setup      : |
    %configure --disable-static \
               --with-ca-certificates=/etc/ssl/certs/ca-certificates.crt \
               --prefix=/usr \
               --disable-more-warnings
build      : |
    unset LD_AS_NEEDED
    %make
install    : |
    unset LD_AS_NEEDED
    %make_install
