name       : glib-networking
version    : 2.56.0
release    : 20
source     :
    - https://download.gnome.org/sources/glib-networking/2.56/glib-networking-2.56.0.tar.xz : 47fd10bcae2e5039dc5f685e3ea384f48e64a6bee26d755718f534a978477c93
homepage   : http://www.gnome.org
license    : GPL-2.0-only
component  : network.base
summary    : The GLib Networking package contains Network related gio modules for GLib.
description: |
    The GLib Networking package contains Network related gio modules for GLib.
emul32     : yes
builddeps  :
    - pkgconfig32(glib-2.0)
    - pkgconfig32(gnutls)
    - pkgconfig32(libtasn1)
    - pkgconfig32(nettle)
    - pkgconfig32(nettle)
    - pkgconfig32(p11-kit-1)
    - pkgconfig(libtasn1)
    - pkgconfig(nettle)
    - gmp-32bit-devel
    - libtool-32bit
    - libunistring-32bit-devel
setup      : |
    %meson_configure -Dca_certificates_path=/etc/ssl/certs/ca-certificates.crt \
           -Dgnome_proxy_support=false \
           -Dinstalled_tests=false \
           -Dlibproxy_support=false \
           -Dstatic_modules=false
build      : |
    unset LD_AS_NEEDED
    %ninja_build
install    : |
    unset LD_AS_NEEDED
    %ninja_install
    # Because they don't seem to care even if you disable it.
    rm -r $installdir/usr/share/installed-tests
